version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: d1g1tsdocker/gazpromorgchart_backend:latest
    command: >
      sh -c "
      python gazpromorgchart/manage.py makemigrations &&
      python gazpromorgchart/manage.py migrate &&
      echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@admin.ru', 'admin')\" | python gazpromorgchart/manage.py shell &&
      python gazpromorgchart/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: