# Generated by Django 4.2.4 on 2024-08-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_departments', to='users.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='teams', to='users.user'),
        ),
    ]
