# Generated by Django 5.0.7 on 2024-08-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programming_skills',
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='id',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_contacts', to='users.contact', verbose_name='Контакты'),
        ),
    ]
