# Generated by Django 5.0.8 on 2024-08-13 13:37

import core.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.PositiveIntegerField(default=core.users.models.generate_department_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itcomponent',
            name='id',
            field=models.PositiveIntegerField(default=core.users.models.generate_it_component_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.PositiveIntegerField(default=core.users.models.generate_team_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveIntegerField(default=core.users.models.generate_user_id, primary_key=True, serialize=False),
        ),
    ]
