# Generated by Django 4.2.4 on 2024-08-05 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность пользователя'),
        ),
    ]
