# Generated by Django 5.0.7 on 2024-08-02 10:04

import core.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contacts',
            field=models.JSONField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='users',
            name='programs',
            field=models.JSONField(blank=True, default=list, null=True, validators=[core.users.validators.validate_hashtags], verbose_name='Программы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='skills',
            field=models.JSONField(blank=True, null=True, validators=[core.users.validators.validate_hashtags], verbose_name='Навыки'),
        ),
    ]
