# Generated by Django 5.0.7 on 2024-08-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_programming_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programming_skills',
            field=models.ManyToManyField(blank=True, to='users.programmingskills', verbose_name='Навыки программирования'),
        ),
    ]
