# Generated by Django 4.2.4 on 2024-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_link1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_link2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_link3',
        ),
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.JSONField(blank=True, default=list, verbose_name='Электронные почты'),
        ),
        migrations.AddField(
            model_name='contact',
            name='links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.JSONField(blank=True, default=list, verbose_name='Телефоны'),
        ),
    ]
