name: Deploy to Remote Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/gazpromorgchart_backend:latest .
        sudo docker push ${{ secrets.DOCKER_USERNAME }}/gazpromorgchart_backend:latest

    - name: Add SSH key
      run: |
        sudo mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | sudo tee ~/.ssh/id_rsa > /dev/null
        sudo chmod 600 ~/.ssh/id_rsa

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_LOGIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo systemctl status docker || sudo systemctl start docker
          cd /home/workshop/gazprom/
          sudo docker-compose -f docker-compose.production.yml pull
          sudo docker-compose -f docker-compose.production.yml up -d